Guianet/Models/AdvertTypes.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guianet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdvertTypes
    {
        public AdvertTypes()
        {
            this.ClientAdvertCategories = new HashSet<ClientAdvertCategories>();
        }
    
        public byte AdvertTypeId { get; set; }
        public string Description { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<ClientAdvertCategories> ClientAdvertCategories { get; set; }
    }
}

Guianet/Models/Adverts.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guianet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adverts
    {
        public Adverts()
        {
            this.ClientAdverts = new HashSet<ClientAdverts>();
        }
    
        public int AdvertId { get; set; }
        public string AdvertName { get; set; }
        public string AdvertDescription { get; set; }
        public string AdvertFile { get; set; }
        public string BaseURL { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<ClientAdverts> ClientAdverts { get; set; }
    }
}

Guianet/Models/Brands.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guianet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Brands
    {
        public Brands()
        {
            this.ClientBrands = new HashSet<ClientBrands>();
        }
    
        public int BrandId { get; set; }
        public string BrandName { get; set; }
        public string Logo { get; set; }
        public bool Active { get; set; }
        public string BaseURL { get; set; }
        public Nullable<byte> AlphabetId { get; set; }
    
        public virtual Alphabet Alphabet { get; set; }
        public virtual ICollection<ClientBrands> ClientBrands { get; set; }
    }
}

Guianet/Models/ClientAddresses.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guianet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientAddresses
    {
        public ClientAddresses()
        {
            this.ClientPhones = new HashSet<ClientPhones>();
        }
    
        public int ClientId { get; set; }
        public int AddressId { get; set; }
    
        public virtual Addresses Addresses { get; set; }
        public virtual Clients Clients { get; set; }
        public virtual ICollection<ClientPhones> ClientPhones { get; set; }
    }
}

Guianet/Models/ClientPhones.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guianet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientPhones
    {
        public int ClientPhoneId { get; set; }
        public byte PhoneTypeId { get; set; }
        public string Number { get; set; }
        public string Lada { get; set; }
        public bool Active { get; set; }
        public int ClientId { get; set; }
        public int AddressId { get; set; }
        public string LocationLada { get; set; }
    
        public virtual ClientAddresses ClientAddresses { get; set; }
        public virtual PhoneTypes PhoneTypes { get; set; }
    }
}

Guianet/Models/ClientsByEdition.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Guianet.Models
{
    public class ClientsByEdition
    {
        public int? ClientId { get; set; }
        public string CompanyName { get; set; }
        public string ShortName { get; set; }
        public string Page { get; set; }
        public int? CountAddress { get; set; }
        public int? Location { get; set; }
    }
}

Guianet/Models/ProductAdverts.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guianet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductAdverts
    {
        public ProductAdverts()
        {
            this.ClientProductAdverts = new HashSet<ClientProductAdverts>();
        }
    
        public int ProductAdvertId { get; set; }
        public string ProductAdvertName { get; set; }
        public bool Active { get; set; }
        public string Description { get; set; }
        public string BaseURL { get; set; }
        public int Order { get; set; }
    
        public virtual ICollection<ClientProductAdverts> ClientProductAdverts { get; set; }
    }
}

Guianet/Controllers/Production/ProductionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Guianet.Models;
using Guianet.Models.Sessions;
using System.Data.SqlClient;
using System.IO;
using Newtonsoft.Json;
using System.Xml;
using HtmlAgilityPack;

namespace Guianet.Controllers.Production
{
    public class ProductionController : Controller
    {
        PLMUsers PLMUsers = new PLMUsers();
        GuiaEntities db = new GuiaEntities();
        GetData GetData = new GetData();
        ActivityLog ActivityLog = new ActivityLog();
        CRUD CRUD = new CRUD();
        SegmentContent SegmentContent = new SegmentContent();
        public List<HTMLAttributes> ListAttributesAsoc = new List<HTMLAttributes>();
        ClassReplace ClassReplace = new ClassReplace();



        public ActionResult Index(string CountryId, string ClientId, string EditionId, string BookId, string ProductName)
        {
            SessionProduction ind = (SessionProduction)Session["SessionProduction"];

            if (!Request.IsAuthenticated)
            {
                return RedirectToAction("Logout", "Login");
            }

            if (CountryId != null)
            {
                int Country = int.Parse(CountryId);
                int Client = int.Parse(ClientId);
                int Edition = int.Parse(EditionId);
                int Book = int.Parse(BookId);

                var li = db.Database.SqlQuery<ParticipantProductsClasif>("plm_spGetParticipantProductsToClasification @ClientId=" + Client + ", @EditionId=" + Edition + ", @ProductName='" + ProductName + "'").ToList();

                SessionProduction SessionProduction = new SessionProduction(Country, Client, Edition, Book, null);
                Session["SessionProduction"] = SessionProduction;


                if (!string.IsNullOrEmpty(ProductName))
                {
                    SearchProductNameCL SearchProductNameCL = new SearchProductNameCL(ProductName);
                    Session["SearchProductNameCL"] = SearchProductNameCL;
                }
                else
                {
                    Session["SearchProductNameCL"] = null;
                }

                return View(li);
            }

            if (ind != null)
            {
                int Country = ind.CId;
                int Client = ind.ClId;
                int Edition = ind.EId;
                int Book = ind.BId;

                var li = db.Database.SqlQuery<ParticipantProductsClasif>("plm_spGetParticipantProductsToClasification @ClientId=" + Client + ", @EditionId=" + Edition + ", @ProductName='" + ProductName + "'").ToList();

                SessionProduction SessionProduction = new SessionProduction(Country, Client, Edition, Book, null);
                Session["SessionProduction"] = SessionProduction;

                if (!string.IsNullOrEmpty(ProductName))
                {
                    SearchProductNameCL SearchProductNameCL = new SearchProductNameCL(ProductName);
                    Session["SearchProductNameCL"] = SearchProductNameCL;
                }
                else
                {
                    Session["SearchProductNameCL"] = null;
                }

                return View(li);
            }
            else
            {
                var li = db.Database.SqlQuery<ParticipantProductsClasif>("plm_spGetParticipantProductsToClasification @ClientId=" + 0 + ", @EditionId=" + 0 + "").ToList();

                return View(li);
            }

        }

        public JsonResult EditProduct(string Product, string ProductName, string Register, string BarCode, string Client, string BarCodeI)
        {
            int ProductId = int.Parse(Product);
            int ClientId = int.Parse(Client);

            string Letter = ProductName.Substring(0, 1);

            int AlphabetId = GetData.GetAlphabetId(Letter);

            var _prods = db.Products.Where(x => x.ProductName.Trim() == ProductName.Trim() && x.ProductId != ProductId).ToList();

            if (_prods.LongCount() > 0)
            {
                return Json("_existProduct", JsonRequestBehavior.AllowGet);
            }

            try
            {
                if (!string.IsNullOrEmpty(Register.Trim()))
                {
                    var _resultCP = db.Database.SqlQuery<ClientProducts>("plm_spCRUDClientProducts @CRUDType=" + CRUD.Read + ", @ProductId=" + ProductId + ", @ClientId=" + ClientId + ", @RegisterSanitary='" + Register + "'").ToList();

                    if (_resultCP.LongCount() > 0)
                    {
                        if (!string.IsNullOrEmpty(Register))
                        {
                            var _resultInsertCP = db.Database.ExecuteSqlCommand("plm_spCRUDClientProducts @CRUDType=" + CRUD.Update + ", @ProductId=" + ProductId + ", @ClientId=" + ClientId + ", @RegisterSanitary='" + Register + "'");
                        }
                        else
                        {
                            var _resultInsertCP = db.Database.ExecuteSqlCommand("plm_spCRUDClientProducts @CRUDType=" + CRUD.Update + ", @ProductId=" + ProductId + ", @ClientId=" + ClientId + ", @RegisterSanitary='" + null + "'");
                        }

                        ActivityLog.createClientProducts(ProductId, ClientId, Register, 2);
                    }
                }
                else
                {
                    var _resultCP = db.Database.SqlQuery<ClientProducts>("plm_spCRUDClientProducts @CRUDType=" + CRUD.Read + ", @ProductId=" + ProductId + ", @ClientId=" + ClientId + ", @RegisterSanitary='" + null + "'").ToList();

                    if (_resultCP.LongCount() > 0)
                    {
                        if (!string.IsNullOrEmpty(Register))
                        {
                            var _resultInsertCP = db.Database.ExecuteSqlCommand("plm_spCRUDClientProducts @CRUDType=" + CRUD.Update + ", @ProductId=" + ProductId + ", @ClientId=" + ClientId + ", @RegisterSanitary='" + Register + "'");
                        }
                        else
                        {
                            var _resultInsertCP = db.Database.ExecuteSqlCommand("plm_spCRUDClientProducts @CRUDType=" + CRUD.Update + ", @ProductId=" + ProductId + ", @ClientId=" + ClientId + ", @RegisterSanitary='" + null + "'");
                        }
                        ActivityLog.createClientProducts(ProductId, ClientId, Register, 2);
                    }
                }

            }
            catch (SqlException e)
            {
                string _error = e.Message;

                if (_error == "_RegisterSanitaryExist")
                {
                    return Json("_RegisterSanitaryExist", JsonRequestBehavior.AllowGet);
                }
            }
            if (!string.IsNullOrEmpty(BarCode.Trim()))
            {
                if (!string.IsNullOrEmpty(BarCodeI))
                {
                    int BarCodeId = int.Parse(BarCodeI);

                    try
                    {
                        var _resultBC = db.Database.SqlQuery<BarCodes>("plm_spCRUDBarCodes @CRUDType=" + CRUD.Read + ", @BarCode='" + BarCode + "', @ClientId=" + ClientId + ", @ProductId=" + ProductId + ", @BarCodeId=" + BarCodeId + "").ToList();
                    }
                    catch (SqlException e)
                    {
                        string message = e.Message;

                        if (message == "_alreadyexistBarCode")
                        {
                            return Json("_alreadyexistBarCode", JsonRequestBehavior.AllowGet);
                        }

                        if (message == "_updateBarCode")
                        {
                            try
                            {
                                var _resultBC = db.Database.ExecuteSqlCommand("plm_spCRUDBarCodes @CRUDType=" + CRUD.Update + ", @BarCode='" + BarCode + "', @ClientId=" + ClientId + ", @ProductId=" + ProductId + ", @BarCodeId=" + BarCodeId + "");

                                ActivityLog.createBarCodes(BarCodeId, BarCode, ClientId, ProductId, 2);
                            }
                            catch (Exception ex)
                            {
                                string _errormessage = ex.Message;

                                if (_errormessage == "_existBarCode")
                                {
                                    return Json("_existBarCode", JsonRequestBehavior.AllowGet);
                                }
                            }
                        }

                        if (message == "_notexistBarCode")
                        {
                            try
                            {
                                var _resultBC = db.Database.ExecuteSqlCommand("plm_spCRUDBarCodes @CRUDType=" + CRUD.Create + ", @BarCode='" + BarCode + "', @ClientId=" + ClientId + ", @ProductId=" + ProductId + ", @BarCodeId=" + BarCodeId + "");

                                ActivityLog.createBarCodes(BarCodeId, BarCode, ClientId, ProductId, 1);

                                ActivityLog.createClientProductBarCodes(BarCodeId, ClientId, ProductId, 1);
                            }
                            catch (Exception ex)
                            {
                                string _errormessage = ex.Message;
                            }
                        }
                    }
                }
                else
                {
                    try
                    {
                        var _resultBC = db.Database.ExecuteSqlCommand("plm_spCRUDBarCodes @CRUDType=" + CRUD.Create + ", @BarCode='" + BarCode + "', @ClientId=" + ClientId + ", @ProductId=" + ProductId + "");

                        var bc = db.BarCodes.Where(x => x.BarCode.ToUpper().Trim() == BarCode.ToUpper().Trim()).ToList();

Guianet/Views/Production/BrandImages.cshtml
@model IEnumerable<BrandImagesByEditionByClientByProduct>
@using Guianet.Models;

@{
    ViewBag.Title = "Brands";
    WebGrid _datagrid = new WebGrid(Model, rowsPerPage: 20);
    Guianet.Models.Sessions.SessionBrandsProd ind = (Guianet.Models.Sessions.SessionBrandsProd)Session["SessionBrandsProd"];
    GuiaEntities db = new GuiaEntities();
    int ClientIdss, EditionIds, BookIds, CountryIdss, BrandIds;
    if (ind != null)
    {
        ClientIdss = ind.ClId;
        EditionIds = ind.EId;
        BookIds = ind.BId;
        CountryIdss = ind.CId;
        BrandIds = Convert.ToInt32(ind.PId);
    }
    else
    {
        ClientIdss = 0;
        EditionIds = 0;
        BookIds = 0;
        CountryIdss = 0;
        BrandIds = 0;
    }
}
<br />
<br />
<ol class="breadcrumb">
    <li><a href="@Url.Content("~/Production/Brands")" class="ldr">Producción</a></li>
    <li><a href="@Url.Content("~/Production/Brands")" class="ldr">Marcas</a></li>
    <li class="active">Agregar Imagen</li>
</ol>
<div class="row">
    <div class="col-lg-6">
        @{
            if (ind != null)
            {
                <table class="widthtable table-hover">

                    <tr>
                        <td style="width: 6%;"><label class="labelsform">País:</label></td>
                        <td>
                            @{
                var cts = (from _ct in db.Countries
                           where _ct.CountryId == CountryIdss
                           select _ct).ToList();
                foreach (Countries _ct in cts)
                {
                    <span class="spans">@_ct.CountryName</span>
                                <input type="text" id="CountryId" value="@_ct.CountryId" style="display:none"/>
                }
                            }
                        </td>
                    </tr>
                    <tr>
                        <td style="width:6%"><label class="labelsform">Libro:</label></td>
                        <td>
                            @{
                var bks = (from _bk in db.Books
                           where _bk.BookId == BookIds
                           select _bk).ToList();
                foreach (Books _bks in bks)
                {
                    <span class="spans">@_bks.BookName</span>
                }
                            }
                        </td>
                    </tr>
                    <tr>
                        <td style="width:6%"><label class="labelsform">Edición:</label></td>
                        <td>
                            @{
                var eds = (from _ed in db.Editions
                           where _ed.EditionId == EditionIds
                           select _ed).ToList();
                foreach (Editions _eds in eds)
                {
                    <span class="spans">@_eds.NumberEdition</span>
                                <input type="text" value="@_eds.EditionId" id="EditionId" style="display:none" />
                }
                            }
                        </td>
                    </tr>
                    <tr>
                        <td style="width:6%"><label class="labelsform">Cliente:</label></td>
                        <td>
                            @{
                var cl = (from _cl in db.Clients
                          where _cl.ClientId == ClientIdss
                          select _cl).ToList();
                foreach (Clients _cl in cl)
                {
                    <span class="spans">@_cl.CompanyName</span>
                                <input type="text" value="@_cl.ClientId" id="ClientId" style="display:none" />
                }
                            }
                        </td>
                    </tr>
                    <tr>
                        <td style="width:6%"><label class="labelsform">Marca:</label></td>
                        <td>
                            @{
                var br = (from _br in db.Brands
                          where _br.BrandId == BrandIds
                          select _br).ToList();
                foreach (Brands _br in br)
                {
                    <span class="spans">@_br.BrandName</span>
                                <input type="text" value="@_br.BrandId" id="BrandId" style="display:none" />
                }
                            }
                        </td>
                    </tr>
                </table>
            }
        }
    </div>
    <div class="col-lg-6" style="text-align:center">
        <button class="btn btn-primary ldr" onclick="location.href='@Url.Content("~/Production/Brands")';return false;">
            <span class="glyphicon glyphicon-home"></span>
            <span>&nbsp; Regresar</span>
        </button>
    </div>
</div>
<br />
<div style="display:normal;border:none; width:50%;margin-left:25%" id="DivAddHTMLFile">
    <form enctype="multipart/form-data" method="post" id="SendBrandImages">
        <div class="input-group">
            <label class="input-group-btn">
                <span class="btn btn-primary">
                    Browse&hellip;
                </span>
                <input id="uploadBtn" type="file" accept="image/png" name="file" style="display:none" onchange="addBrandName($(this))" />
            </label>
            <input type="text" class="form-control" readonly id="txtFileName">
        </div>
    </form>
    <br />
    <br />
    <button style="float:right" class="btn btn-danger btn-sm" onclick="CancelSaveBrand($(this))">
        <span class="glyphicon glyphicon-remove"></span>
        <span>&nbsp; Cancelar</span>
    </button>
    <button style="float:right" class="btn btn-primary btn-sm" onclick="SaveBrandImage($(this))">
        <span class="glyphicon glyphicon-saved"></span>
        <span>&nbsp; Guardar</span>&nbsp;&nbsp;
    </button>
</div>
<br />
<br />
<br />
<br />
<br />
<br />
<div class="widthtable">
    <table class="widthtable">
        <thead class="webgrid-header">
            <tr>
                <th>Nombre de Imagen</th>
                <th>Imagen</th>
            </tr>
        </thead>
        <tbody>
            @{
                foreach(BrandImagesByEditionByClientByProduct _br in Model)
                {
                    <tr>
                        <td style="width:75%">
                            <label style="font-size:12px">
                                @_br.Logo
                            </label>
                        </td>
                        <td style="width:20%">
                            <div class="responsive-container" id="DivAdvertImage">
                                <div class="img-container">
                                    <img src="@Url.Action("GetBrandImages", "Production", new { BrandId = _br.BrandId, CountryId = CountryIdss })" class="aiimg" style="width: 70px; height: 70px" />
                                </div>
                            </div>
                        </td>
                    </tr>   
                }
            }
        </tbody>
    </table>
</div>