Guianet/Controllers/LI/LIController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Guianet.Models;
using Guianet.Models.Sessions;
using Newtonsoft.Json;
using System.Text;

namespace Guianet.Controllers.LI
{

    public class LIController : Controller
    {
        GuiaEntities db = new GuiaEntities();
        ActivityLog ActivityLog = new ActivityLog();
        PLMUsers dbUsers = new PLMUsers();
        CRUD CRUD = new CRUD();
        GetData GetData = new GetData();

        public ActionResult Index(string CountryId, string ClientId, string EditionId, string BookId, string ProductName)
        {
            SessionClasification ind = (SessionClasification)Session["SessionClasification"];
            SessionTypesLI Types = (SessionTypesLI)Session["SessionTypesLI"];

            if (!Request.IsAuthenticated)
            {
                return RedirectToAction("Logout", "Login");
            }

            if (CountryId != null)
            {
                int Country = int.Parse(CountryId);
                int Client = int.Parse(ClientId);
                int Edition = int.Parse(EditionId);
                int Book = int.Parse(BookId);

                var li = db.Database.SqlQuery<ParticipantProductsClasif>("plm_spGetParticipantProductsToClasification @ClientId=" + Client + ", @EditionId=" + Edition + ", @ProductName='" + ProductName + "'").ToList();

                SessionClasification SessionClasification = new SessionClasification(Country, Client, Edition, Book, null);
                Session["SessionClasification"] = SessionClasification;

                if (Types != null)
                {
                    if (Types.Types == "Clasif")
                    {
                        li = li.Where(x => x.Qtty != 0).ToList();
                    }

                    if (Types.Types == "Ok")
                    {
                        li = li.Where(x => x.Validation != 0).ToList();
                    }

                    if (Types.Types == "NotClasif")
                    {
                        li = li.Where(x => x.Qtty == 0).ToList();
                    }

                    if (Types.Types == "NotOk")
                    {
                        li = li.Where(x => x.Validation == 0).ToList();
                    }

                    if (Types.Types == "CCS")
                    {

                        li = (from l in li
                              join w in db.Works
                                  on l.ProductId equals w.ProductId
                              where w.ClientId == Client
                              select l).Distinct().ToList();

                    }

                    if (Types.Types == "NotCCS")
                    {

                        li = (from l in li
                              from w in db.Works.Where(x => x.ProductId == l.ProductId && x.ClientId == Client).DefaultIfEmpty()
                              where w == null
                              select l).Distinct().ToList();

                    }
                }

                if (!string.IsNullOrEmpty(ProductName))
                {
                    SearchProductNameCL SearchProductNameCL = new SearchProductNameCL(ProductName);
                    Session["SearchProductNameCL"] = SearchProductNameCL;
                }
                else
                {
                    Session["SearchProductNameCL"] = null;
                }

                return View(li);
            }

            if (ind != null)
            {
                int Country = ind.CId;
                int Client = ind.ClId;
                int Edition = ind.EId;
                int Book = ind.BId;

                var li = db.Database.SqlQuery<ParticipantProductsClasif>("plm_spGetParticipantProductsToClasification @ClientId=" + Client + ", @EditionId=" + Edition + ", @ProductName='" + ProductName + "'").ToList();

                SessionClasification SessionClasification = new SessionClasification(Country, Client, Edition, Book, null);
                Session["SessionClasification"] = SessionClasification;

                if (Types != null)
                {
                    if (Types.Types == "Clasif")
                    {
                        li = li.Where(x => x.Qtty != 0).ToList();
                    }

                    if (Types.Types == "Ok")
                    {
                        li = li.Where(x => x.Validation != 0).ToList();
                    }

                    if (Types.Types == "NotClasif")
                    {
                        li = li.Where(x => x.Qtty == 0).ToList();
                    }

                    if (Types.Types == "NotOk")
                    {
                        li = li.Where(x => x.Validation == 0).ToList();
                    }

                    if (Types.Types == "CCS")
                    {

                        li = (from l in li
                              join w in db.Works
                                  on l.ProductId equals w.ProductId
                              where w.ClientId == Client
                              select l).Distinct().ToList();

                    }

                    if (Types.Types == "NotCCS")
                    {
                        li = (from l in li
                              from w in db.Works.Where(x => x.ProductId == l.ProductId && x.ClientId == Client).DefaultIfEmpty()
                              where w == null
                              select l).Distinct().ToList();
                    }
                }

                if (!string.IsNullOrEmpty(ProductName))
                {
                    SearchProductNameCL SearchProductNameCL = new SearchProductNameCL(ProductName);
                    Session["SearchProductNameCL"] = SearchProductNameCL;
                }
                else
                {
                    Session["SearchProductNameCL"] = null;
                }

                return View(li);
            }
            else
            {
                var li = db.Database.SqlQuery<ParticipantProductsClasif>("plm_spGetParticipantProductsToClasification @ClientId=" + 0 + ", @EditionId=" + 0 + "").ToList();

                return View(li);
            }

        }

        public ActionResult ClasificationProducts(int? ProductId)
        {
            SessionClasification ind = (SessionClasification)Session["SessionClasification"];

            if (ind == null)
            {
                return RedirectToAction("Logout", "Login");
            }

            int _clientid = ind.ClId;

            ind.PId = ProductId;

            var cc = db.Database.SqlQuery<HomogeneousCategoriesByClientByProduct>("plm_spGetProductCategoriesByClientByProduct  @ProductId =" + ProductId + ",  @ClientId= " + _clientid + "").ToList();

            return View(cc);
        }

        public JsonResult getlevel4(string HomogeneousCategory, string Client, string Product)
        {
            List<GetHomogeneousCategories> Cats = new List<GetHomogeneousCategories>();
            SearchCategoryCL SearchCategory = (SearchCategoryCL)Session["SearchCategoryCL"];

            if (SearchCategory != null)
            {
                int HomogeneousCategoryId = int.Parse(HomogeneousCategory);
                int ClientId = int.Parse(Client);
                int ProductId = int.Parse(Product);

                Cats = db.Database.SqlQuery<GetHomogeneousCategories>("plm_spGetCategoryThree @HomogeneousCategoryId=" + HomogeneousCategoryId + ", @TextSearch='" + SearchCategory.CategoryName + "', @ClientId=" + ClientId + ",@ProductId=" + ProductId + "").ToList();
            }
            else
            {
                int HomogeneousCategoryId = int.Parse(HomogeneousCategory);
                int ClientId = int.Parse(Client);
                int ProductId = int.Parse(Product);

                Cats = db.Database.SqlQuery<GetHomogeneousCategories>("plm_spGetCategoryThree @HomogeneousCategoryId=" + HomogeneousCategoryId + ", @ClientId=" + ClientId + ",@ProductId=" + ProductId + "").ToList();
            }

            return Json(Cats, JsonRequestBehavior.AllowGet);
        }

        public JsonResult saveCategories(String ListItems, string ArraySize, string Edition)
        {
            dynamic d = JsonConvert.DeserializeObject(ListItems);

            int Size = int.Parse(ArraySize);
            int EditionId = int.Parse(Edition);

            for (var i = 0; i <= Size - 1; i++)
            {
                var Id = Convert.ToInt32(d[i]["Id"]);
                var CId = Convert.ToInt32(d[i]["CId"]);
                var PId = Convert.ToInt32(d[i]["PId"]);
                var HCId = Convert.ToInt32(d[i]["HCId"]);

                string a = insertProductLeafCategories(CId, PId, Id, HCId);
                bool r = AddEditionCategoryThree(EditionId, HCId);
            }
            return Json(true, JsonRequestBehavior.AllowGet);
        }

        public bool AddEditionCategoryThree(int EditionId, int CategoryThreeId)
        {
            List<GetEditionCategoryThree> ec = db.Database.SqlQuery<GetEditionCategoryThree>("plm_spCRUDEditionCategoryThree @CRUDType=" + CRUD.Read + ", @EditionId=" + EditionId + ", @CategoryThreeId=" + CategoryThreeId + "").ToList();

            if (ec.LongCount() == 0)
            {
                var result = db.Database.ExecuteSqlCommand("plm_spCRUDEditionCategoryThree @CRUDType=" + CRUD.Create + ", @EditionId=" + EditionId + ", @CategoryThreeId=" + CategoryThreeId + "");

                ActivityLog.EditionCategoryThree(EditionId, CategoryThreeId, null, null, 1);
            }

            return true;
        }

        public string insertProductLeafCategories(int ClientId, int ProductId, int LeafCategoryId, int CategoryThreeId)
        {
            CountriesUsers user = (CountriesUsers)Session["CountriesUsers"];
            int ApplicationId = user.ApplicationId;
            int UsersId = user.userId;

Guianet/Views/LI/Categories.cshtml
@model IEnumerable<GetHomogeneousCategories>
@using Guianet.Models;
@{
    ViewBag.Title = "Categories";
    GuiaEntities db = new GuiaEntities();
    List<GetHomogeneousCategories> Cats = new List<GetHomogeneousCategories>();
}

<br />
<br />
<ol class="breadcrumb">
    <li><a href="@Url.Content("~/LI/Categories")" class="ldr">LI</a></li>
    <li class="active">Categorías</li>
</ol>
<br />
<br />

<button class="btn btn-success" onclick="OpenformAddCategoryLevel3()">
    <span class="glyphicon glyphicon-upload"></span>
    <span>&nbsp; Agregar tercer nivel</span>
</button>

<br />
<br />
<br />
<br />
<div class="row">
    <div class="col-lg-5">
        <div>
            <div class="scrollbar1">
                @{
                    <ul style="list-style: none;">
                        @foreach (GetHomogeneousCategories _cat in Model)
                    {
                            <li>
                                <button class="btn btn-success btn-sm" style="border-radius:50%" value="@_cat.HomogeneousCategory" onclick="GetDataAddCategory(@_cat.HomogeneousCategoryId, $(this))">
                                    <span class="glyphicon glyphicon-plus" style="position:static"></span>
                                </button>
                                <span class="glyphicon glyphicon-plus" id="Expand_@_cat.HomogeneousCategoryId" onclick="getlevel4LI(@_cat.HomogeneousCategoryId)" style="cursor:pointer"></span>
                                <span class="glyphicon glyphicon-minus" style="display:none;cursor:pointer" id="Collapse_@_cat.HomogeneousCategoryId" onclick="collapselevel4LI(@_cat.HomogeneousCategoryId)"></span>
                                <label style="font-weight:100;cursor:pointer" data-toggle="tooltip" title="Doble click en el Nombre para Editar @_cat.HomogeneousCategory" ondblclick="OpenEditCategory($('@_cat.HomogeneousCategoryId'),$('@_cat.HomogeneousCategory'))">@_cat.HomogeneousCategory</label>
                                <ul id="ListL2_@_cat.HomogeneousCategoryId" style='margin-left:30px; list-style:initial'></ul>
                            </li>
                    }
                    </ul>
                }
            </div>
        </div>
    </div>
    <div class="col-lg-7" style="border:none">
        <div class="modal-dialog" id="ModalAddCategory" style="display:none">
            <div class="modal-content">
                <div class="modal-header label-primary">
                    <h4 class="modal-title" id="TextCategoryName" style="font-style:italic"></h4>
                    <input type="text" class="form-control" id="TextCategoryId" style="display:none"/>
                </div>
                <div class="modal-body">
                    <br />
                    <div class="row" style="vertical-align:bottom">
                        <div class="labelsform col-lg-2">
                            Categoría:
                        </div>
                        <div class="col-lg-10">
                            <div class="form-group has-feedback" id="divCategoryName" style="margin-bottom: 0;">
                                <input type="text" class="form-control" id="CategoryName" style="text-transform:uppercase" placeholder="Categoría" onkeypress="removerequieredfieldCats()" />
                                <span class="glyphicon glyphicon-remove form-control-feedback errorC" style="display:none"></span>
                            </div>
                        </div>
                    </div>
                    <br />
                    <div class="alert alert-success" id="AlertSuccess" style="display:none">
                       <span class="glyphicon glyphicon-ok"></span> <span>&nbsp; La Categoría se agrego correctamente.</span>
                    </div>
                    <div class="alert alert-danger" id="AlertError" style="display:none">
                        <span class="glyphicon glyphicon-remove"></span> <span>&nbsp; La Categoría ya existe.</span>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary" data-dismiss="modal" onclick="SaveCategory()">
                        <span class="glyphicon glyphicon-ok"></span>
                        <span>&nbsp; Guardar</span>
                    </button>
                    <button type="button" class="btn btn-danger" data-dismiss="modal" onclick="CancelAddCategory()">
                        <span class="glyphicon glyphicon-remove"></span>
                        <span>&nbsp; Cancelar</span>
                    </button>
                </div>
            </div>

        </div>

        <div class="modal-dialog" id="ModalAddCategoryThree" style="display:none">
            <div class="modal-content">
                <div class="modal-header label-primary">
                    <h4 class="modal-title" style="font-style:italic">CATEGORÍA NIVEL 3</h4>
                </div>
                <div class="modal-body">
                    <br />
                    <div class="row" style="vertical-align:bottom">
                        <div class="labelsform col-lg-2">
                            Categoría:
                        </div>
                        <div class="col-lg-10">
                            <div class="form-group has-feedback" id="divCategoryName3" style="margin-bottom: 0;">
                                <input type="text" class="form-control" id="CategoryName3" style="text-transform:uppercase" placeholder="Categoría" onkeypress="removerequieredfieldCats3()" />
                                <span class="glyphicon glyphicon-remove form-control-feedback errorC3" style="display:none"></span>
                            </div>
                        </div>
                    </div>
                    <br />
                    <div class="alert alert-success" id="AlertSuccess3" style="display:none">
                        <span class="glyphicon glyphicon-ok"></span> <span>&nbsp; La Categoría se agrego correctamente.</span>
                    </div>
                    <div class="alert alert-danger" id="AlertError3" style="display:none">
                        <span class="glyphicon glyphicon-remove"></span> <span>&nbsp; La Categoría ya existe.</span>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary" data-dismiss="modal" onclick="SaveCategory3()">
                        <span class="glyphicon glyphicon-ok"></span>
                        <span>&nbsp; Guardar</span>
                    </button>
                    <button type="button" class="btn btn-danger" data-dismiss="modal" onclick="CancelAddCategory3()">
                        <span class="glyphicon glyphicon-remove"></span>
                        <span>&nbsp; Cancelar</span>
                    </button>
                </div>
            </div>

        </div>
    </div>
</div>

<button id="BtnEditCategory" data-toggle="modal" data-target="#ModalEditCategory" style="display:none"></button>
<div class="modal fade" id="ModalEditCategory" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header label-primary">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h3 class="modal-title" style="color:white" id="messageerror"><i>Editar Categoría</i></h3>
            </div>
            <div class="modal-body" id="contenteditions">
                <input type="text" id="inputCategoryThreeId" style="display:none" />
                <input type="text" id="InputCategoryThree" class="form-control" style="color:red;text-transform:uppercase"/>
            </div>
            <div class="modal-footer" id="divbtncloseerror">
                <button class="btn btn-primary" onclick="EditCategoriesLI()">
                    <span class="glyphicon glyphicon-ok"></span>
                    <span>&nbsp; Aceptar</span>
                </button>
                <button class="btn btn-default" data-dismiss="modal">
                    <span class="glyphicon glyphicon-remove"></span>
                    <span>&nbsp; Cancelar</span>
                </button>
            </div>
        </div>
    </div>
</div>

<button id="BtnEditLeafCategory" data-toggle="modal" data-target="#ModalEditLeafCategory" style="display:none"></button>
<div class="modal fade" id="ModalEditLeafCategory" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header label-primary">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h3 class="modal-title" style="color:white" id="messageerror"><i>Editar Categoría</i></h3>
            </div>
            <div class="modal-body" id="contenteditions">
                <input type="text" id="inputLeafCategoryId" style="display:none" />
                <input type="text" id="InputLeafCategory" class="form-control" style="color:red;text-transform:uppercase" />
            </div>
            <div class="modal-footer" id="divbtncloseerror">
                <button class="btn btn-primary" onclick="EditLeafCategoriesLI()">
                    <span class="glyphicon glyphicon-ok"></span>
                    <span>&nbsp; Aceptar</span>
                </button>
                <button class="btn btn-default" data-dismiss="modal">
                    <span class="glyphicon glyphicon-remove"></span>
                    <span>&nbsp; Cancelar</span>
                </button>
            </div>
        </div>
    </div>
</div>

Guianet/Views/LI/ClasificationProducts.cshtml
@model IEnumerable<Guianet.Models.HomogeneousCategoriesByClientByProduct>
@using Guianet.Models;
@using Guianet.Models.Sessions;
@{
    ViewBag.Title = "ClasificationProducts";
    List<GetHomogeneousCategories> Cats = new List<GetHomogeneousCategories>();
    SessionClasification ind = (SessionClasification)Session["SessionClasification"];
    GuiaEntities db = new GuiaEntities();
    SearchCategoryCL SearchCategoryCL = (SearchCategoryCL)Session["SearchCategoryCL"];
    WebGrid _datagridcc = new WebGrid(Model, rowsPerPage: 20);
}
<script src="@Url.Content("~/Scripts/ScriptsSalesModule.js")"></script>
<br />
<br />
<ol class="breadcrumb">
    <li><a href="@Url.Content("~/LI/Index")" class="ldr">LI</a></li>
    <li><a href="@Url.Content("~/LI/Index")" class="ldr">Productos</a></li>
    <li class="active">Clasificación</li>
</ol>
@{
    if (ind != null)
    {
        <table style="width:100%" border="0">
            <tr>
                <td style="width:6%"><label class="labelsform">País: </label> </td>
                <td>
                    @{
        int countryid = ind.CId;
        var countr = from countries in db.Countries
                     where countries.CountryId == countryid
                     select countries;
        foreach (Countries c in countr)
        {
            <span class="spans">@c.CountryName</span><input type="text" style="display: none" id="countryid" class="countryid" value="@c.CountryId" />
        }

                    }
                </td>
                <td rowspan="5" style="text-align:left">
                    <table class="widthtable" border="0">
                        <tr>
                            <td style="text-align:center">
                                <button class="btn btn-primary ldr" onclick="location.href = '@Url.Action("Index", "LI")'; return false;">
                                    <span class="glyphicon glyphicon-home"></span>
                                    <span class="spans">&nbsp; Regresar...</span>
                                </button>
                            </td>
                            <td style="text-align:center">
                                <a target="_blank" href="@Url.Action("GetCategoriesByProductReportLI", "GetReports", new { id = "PDF", ProductId = ind.PId })"><img src="@Url.Content("~/Images/ProductCategories.png")" style="height:75px;width:60px"></a>
                            </td>
                        </tr>
                    </table>
                    

                    
                </td>
            </tr>
            <tr>
                <td><label class="labelsform">Obra:</label></td>
                <td>
                    @{
        int bookid = ind.BId;
        var books = from book in db.Books
                    where book.BookId == bookid
                    select book;
        foreach (Books b in books)
        {
            <span class="spans">@b.BookName</span><input type="text" style="display:none" id="bookn" value="@b.BookId" />
        }
                    }
                </td>
            </tr>
            <tr>
                <td><label class="labelsform">Edición:</label></td>
                <td>
                    @{
        int edition = ind.EId;
        var _edition = from editions in db.Editions
                       where editions.EditionId == edition
                       select editions;
        foreach (Editions e in _edition)
        {
            <span class="spans">@e.NumberEdition</span><input type="text" style="display:none" id="editionid" value="@e.EditionId" />
        }
                    }
                </td>
            </tr>
            <tr>
                <td><label class="labelsform">Cliente:</label></td>
                <td>
                    @{
        int client = ind.ClId;
        var clients = from _clients in db.Clients
                      where _clients.ClientId == client
                      select _clients;
        foreach (Clients c in clients)
        {
            <span class="spans">@c.CompanyName</span><input type="text" style="display:none" id="clientid" value="@c.ClientId" />
        }
                    }
                </td>
            </tr>
            <tr>
                <td><label class="labelsform">Producto:</label></td>
                <td>
                    @{
        int? productid = ind.PId;
        var products = from _products in db.Products
                       where _products.ProductId == productid
                       select _products;
        foreach (Products p in products)
        {
            <span class="spans">@p.ProductName.ToUpper()</span><input type="text" style="display:none" id="ProductId" value="@p.ProductId" />
        }
                    }
                </td>
            </tr>
        </table>
    }
}
<br />
<br />
<div class="row">
    <div class="col-lg-6">
        @*<input type="text" class="form-control" placeholder="Buscar Categorías..."/>*@
        <div class="input-group stylish-input-group">
            @{
                if (SearchCategoryCL != null)
                {
                    <input type="text" class="form-control" placeholder="Buscar Categorías..." id="TextSearch" value="@SearchCategoryCL.CategoryName">
                }
                else
                {
                    <input type="text" class="form-control" placeholder="Buscar Categorías..." id="TextSearch">
                }
            }

            <span class="input-group-addon" style="width:0" onclick="searchCategoriesCL()" id="btnSearchCategories">
                <button type="submit">
                    <span class="glyphicon glyphicon-search"></span>
                </button>
            </span>
        </div>
    </div>
</div>
<br />
<div class="row">
    <div class="col-lg-6">
        <div>
            <button style="float:right" class="btn btn-danger" onclick="saveCategoriesCL()">
                <span class="glyphicon glyphicon-forward"></span>
                <span>&nbsp; Asociar</span>
            </button>
            <div class="scrollbar1">
                @{
                    if (SearchCategoryCL != null)
                    {
                        Cats = db.Database.SqlQuery<GetHomogeneousCategories>("plm_spGetCategoryThree @HomogeneousCategoryId= 0, @TextSearch='" + SearchCategoryCL.CategoryName + "', @ClientId=" + ind.ClId + ", @ProductId=" + ind.PId + "").ToList();
                    }
                    else
                    {
                        Cats = db.Database.SqlQuery<GetHomogeneousCategories>("plm_spGetCategoryThree @HomogeneousCategoryId= 0, @ClientId=" + ind.ClId + ", @ProductId=" + ind.PId + "").ToList();
                    }
                    <ul style="list-style: none;">
                        @foreach (GetHomogeneousCategories _cat in Cats)
                        {
                            <li>

                                <span class="glyphicon glyphicon-plus" id="Expand_@_cat.HomogeneousCategoryId" onclick="getlevel4CL(@_cat.HomogeneousCategoryId)" style="cursor:pointer"></span>

                                <span class="glyphicon glyphicon-minus" style="display:none" id="Collapse_@_cat.HomogeneousCategoryId" onclick="collapselevel4(@_cat.HomogeneousCategoryId)"></span>
                                <label style="font-weight:100">@_cat.HomogeneousCategory</label>
                                <ul id="ListL2_@_cat.HomogeneousCategoryId" style="list-style: none;"></ul>
                            </li>
                        }
                    </ul>
                }
            </div>
        </div>
    </div>
    <br />
    <div class="col-lg-6">
        @_datagridcc.GetHtml(
                              headerStyle: "webgrid-header",
                          footerStyle: "webgrid-footer",
                          alternatingRowStyle: "webgrid-alternating-row",
                          selectedRowStyle: "webgrid-selected-row",
                          rowStyle: "webgrid-row-style",
                          tableStyle: "webgrid-table1",
                          mode: WebGridPagerModes.All,
                          columns: new[] {
                            @*_datagridcc.Column("",header:"Categoría Nivel 1", format: @<text>
                                    <label>&nbsp;@item.CategoryNameL1</label>
                                    <input type="text" style="display:none" value="@item.CategoryIdL1" />
                                </text>),
                                _datagridcc.Column("",header:"Categoría Nivel 2", format: @<text>
                                    <label>&nbsp;@item.CategoryNameL2</label>
                                    <input type="text" style="display:none" value="@item.CategoryIdL2" />
                                </text>),*@
                            _datagridcc.Column("",header:"Categoría Nivel 3", format: @<text>
            <label style="font-weight:100; font-size:12px">&nbsp;&nbsp;@item.HomogeneousCategoryL3</label>
            <input type="text" style="display:none" id="HomogeneousCategoryIdL3" value="@item.HomogeneousCategoryIdL3" />
                            </text>,style:"column47"),
                            _datagridcc.Column("",header:"Categoría Nivel 4", format: @<text>
            <label style="font-weight:100; font-size:12px">&nbsp;@item.LeafCategoryL4</label>
            <input type="text" style="display:none" id="LeafCategoryIdL4" value="@item.LeafCategoryIdL4" />
                            </text>,style:"column47"),
                            _datagridcc.Column("",header:"Eliminar", format: @<text>
            <button class="btn btn-danger btn-sm" onclick="deleteProductLeafCategoriesCL($(this))">
                <span class="glyphicon glyphicon-remove"></span>
            </button>
                            </text>,style:"text-center column5")
                          })
    </div>
</div>
<br />